pages:
  stage: deploy
  script:
 # - mkdir .public
 # - cp -r * .public
 # - mv .public public
  artifacts:
    paths:
    - data
  only:
  - master

 
# command to install dependencies
install: 
    stage: deploy
    script: 
    - apt-get install -y python
    - apt-cache search p
    - apt-get install -y pip
    - pip install -r requirements.txt
test:
    stage: deploy
    script: nosetests tests/proof_of_concept.py