pages:
  stage: deploy
  script:
  - mkdir public
  - cp index.html public
  - cp -r data public
  artifacts:
    paths:
    - public
  only:
  - master

 
# command to install dependencies
install: 
    stage: deploy
    script: 
    - apt-get install -y python
    - apt-cache search p
    - apt-get install -y pip
    - pip install -r requirements.txt
test:
    stage: deploy
    script: nosetests tests/proof_of_concept.py